# Generated by Django 5.2.6 on 2025-10-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='cretrd_by',
            new_name='created_by',
        ),
    ]
