# Generated by Django 5.2.6 on 2025-10-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_updated_at_alter_material_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id_material',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Material ID'),
        ),
    ]
